# Uncomment the next line to define a global platform for your project

platform :ios, '9.0'

target 'cleaner' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for cleaner
  pod 'OpenCV'
  pod 'CocoaImageHashing', :git => 'https://github.com/ameingast/cocoaimagehashing.git'
  pod 'MBProgressHUD', '1.1.0'

end
